POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"email@test.com",
  "password":"a1234"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"unique1@example.com",
  "password":"a1234"
}

### Sign out
POST http://localhost:3000/auth/signout

### Get the currently signed user
GET http://localhost:3000/auth/whoami

### find a particular user with a given ID
GET http://localhost:3000/auth/7

### Find all users with a given email
GET http://localhost:3000/auth?email=second@example.com

### delete a user given id
DELETE http://localhost:3000/auth/2

### update a user
PATCH http://localhost:3000/auth/8
Content-Type: application/json

{
  "password":"a1234"
}