POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"email123@test.com",
  "password":"a1234"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"unique1@example.com",
  "password":"a11115"
}

### Sign out
POST http://localhost:3000/auth/signout

### Get the currently signed user
GET http://localhost:3000/users/whoami

### find a particular user with a given ID
GET http://localhost:3000/users/7

### Find all users with a given email
GET http://localhost:3000/users?email=second@example.com

### delete a user given id
DELETE http://localhost:3000/users/me

### update a user
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "password":"a11115"
}